language: ruby
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
install: 
  - gem install jekyll
  - gem install jekyll-paginate
script: 
  - jekyll build && jekyll s
notifications:
  slack:
    on_success: change
